### ISSUE TITLE
$'\357\273\277' In front of first command

### ISSUE THREAD

**Issue by theboxer** [stecman/symfony-console-completion#61] opened 2015-10-10 20:41 UTC
After hitting tab to get all available commands, first command is prepended with `$'\357\273\277'` and it's unable to trigger it through the completion.

<img width="266" alt="screen shot 2015-10-10 at 22 41 13" src="https://cloud.githubusercontent.com/assets/845220/10413173/0dd18ff4-6fa0-11e5-9987-bcea2c087488.png">

OS X 10.11
Shell: Oh My Zsh

**Comment by stecman** [comment] 2015-10-29 21:51
Hey @theboxer, apparently `\357\273\277` is a UTF8 Byte Order Mark (BOM). I've run a search across this library's source and it doesn't contain this BOM, so it's likely that output is coming from the program you're completing for, or something else in your environment. A fresh install of Oh My Zsh doesn't exhibit this issue on my machine, but it's possible the output could also be coming from a plugin, theme, etc.

You could try [searching your code for any BOMs](http://stackoverflow.com/questions/204765/elegant-way-to-search-for-utf-8-files-with-bom) and removing them. If the source of the command line application you're using is available, a link to that would also help to debug this issue.

**Comment by stecman** [comment] 2016-09-18 23:29
Closing this as there hasn't been any activity for a year, and I'm reasonably sure the issue is explained.

**Closed by stecman** 2016-09-18 23:29 UTC
